version: '3.8'

services:
  backend:
    build: .
    container_name: student_workload_backend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - workload-network

volumes:
  uploads_data:
    driver: local

networks:
  workload-network:
    name: workload-network
    driver: bridge
